// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/recommender/v1beta1/recommendation.proto

package com.google.cloud.recommender.v1beta1;

public interface ImpactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.recommender.v1beta1.Impact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Category that is being targeted.
   * </pre>
   *
   * <code>.google.cloud.recommender.v1beta1.Impact.Category category = 1;</code>
   * @return The enum numeric value on the wire for category.
   */
  int getCategoryValue();
  /**
   * <pre>
   * Category that is being targeted.
   * </pre>
   *
   * <code>.google.cloud.recommender.v1beta1.Impact.Category category = 1;</code>
   * @return The category.
   */
  com.google.cloud.recommender.v1beta1.Impact.Category getCategory();

  /**
   * <pre>
   * Use with CategoryType.COST
   * </pre>
   *
   * <code>.google.cloud.recommender.v1beta1.CostProjection cost_projection = 100;</code>
   * @return Whether the costProjection field is set.
   */
  boolean hasCostProjection();
  /**
   * <pre>
   * Use with CategoryType.COST
   * </pre>
   *
   * <code>.google.cloud.recommender.v1beta1.CostProjection cost_projection = 100;</code>
   * @return The costProjection.
   */
  com.google.cloud.recommender.v1beta1.CostProjection getCostProjection();
  /**
   * <pre>
   * Use with CategoryType.COST
   * </pre>
   *
   * <code>.google.cloud.recommender.v1beta1.CostProjection cost_projection = 100;</code>
   */
  com.google.cloud.recommender.v1beta1.CostProjectionOrBuilder getCostProjectionOrBuilder();

  public com.google.cloud.recommender.v1beta1.Impact.ProjectionCase getProjectionCase();
}
